### ISSUE TITLE
Cant find how to edit the tooltips

### ISSUE THREAD

**Issue by tzuzn** [ProFewGames/CustomCrates#9]
I'd like to translate the Preview and Open Tooltip to German but cant find it anywhere in the yml or the gui.

![2023-01-03_13 39 12](https://user-images.githubusercontent.com/83777527/210359041-118f6481-b3b6-4fbe-90b5-cd12405fd657.png)

**Comment by ProFewGames** [comment]
The hologram lines are modifiable through your crate config located in "-/crates/<your crate>". Please refer to the picture provided below as a reference. The language file is also modifiable through "-/language.yml"

![image](https://user-images.githubusercontent.com/17092603/210359788-70696f90-22f4-49cd-8541-ef22190d236c.png)

**Comment by tzuzn** [comment]
Ty im stupid. I litterally found it 10 min after
